version: '3'

services:
  questdb:
    image: questdb/questdb
    volumes:
      - ./questdb:/var/lib/questdb:rw
    ports:
      - "9005:9005"
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"
  # telegraf:
  #   image: telegraf:1.28-alpine
  #   depends_on:
  #     - questdb
  #   volumes:
  #     # Mount for telegraf config
  #     - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro

