zeromq-push=ch.epfl.gsn.networking.zeromq.ZeroMQWrapperPush
zeromq-sync=ch.epfl.gsn.networking.zeromq.ZeroMQWrapperSync
zeromq-async=ch.epfl.gsn.networking.zeromq.ZeroMQWrapperAsync

remote-api=ch.epfl.gsn.wrappers.general.RemoteRestAPIWrapper
http-get=ch.epfl.gsn.wrappers.general.HttpGetWrapper
serial=ch.epfl.gsn.wrappers.general.SerialWrapper
udp=ch.epfl.gsn.wrappers.general.UDPWrapper
csv=ch.epfl.gsn.wrappers.general.CSVWrapper

memory-usage=ch.epfl.gsn.wrappers.MemoryMonitoringWrapper
system-time=ch.epfl.gsn.wrappers.SystemTime
imagefile=ch.epfl.gsn.wrappers.ImageFileWrapper
backlog=ch.epfl.gsn.wrappers.BackLogWrapper
backlog-stats=ch.epfl.gsn.wrappers.BackLogStatsWrapper
data-mapping=ch.epfl.gsn.wrappers.DataMappingWrapper
system-monitoring=ch.epfl.gsn.wrappers.SystemMonitoringWrapper
sensor-monitoring=ch.epfl.gsn.wrappers.SensorMonitoringWrapper
file-getter=ch.epfl.gsn.wrappers.FileGetterWrapper

remote-rest=ch.epfl.gsn.http.rest.RestRemoteWrapper
local=ch.epfl.gsn.delivery.LocalDeliveryWrapper